services:
  postgres:
    image: postgres:15
    container_name: gerenciador-postgres
    environment:
      POSTGRES_DB: gerenciador_orcamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
